image: fedora:latest

generaltester:
  script:
  - dnf install -y file graphviz python3-pip python3-devel gcc diffutils ncurses curl wget
  - pip3 install python-Levenshtein mypy black py2cfg
  - bash grade.sh
  timeout: 2 hours 30 minutes
  artifacts:
    when: always
    paths:
      - results.txt
    expire_in: 1 month
